### ISSUE TITLE
Add support for Prisma schema highlighting

### ISSUE THREAD

**Issue by jasonkuhrt** [prisma-labs/team#3]
So that when:

1. users put this into their Github READMEs, issue comments, pr comments etc.:

    ```
     ```prisma
    ```

2. or users view a `*.prisma` file in a github repo,

users see nice syntax highlighting. Original but stale-closed attempt here: https://github.com/github/linguist/pull/4579

Active PR: https://github.com/github/linguist/pull/4668

**Comment by Weakky** [comment]
Opened PR: https://github.com/github/linguist/pull/4668

**Comment by Weakky** [comment]
Prisma color is colliding with `DataWeave`. There's an open issue to maybe remove the color proximity test and allow brands/companies to use their own color regardless of proximity with other languages.

Open issue here: https://github.com/github/linguist/issues/4506

**Comment by Weakky** [comment]
PR is merged, it should be released end of October at earliest.

Closing now
